# Site settings
title: Alessandro Cosentino
email: 
description: "PhD student"
baseurl: ""
url: "https://cs.uwaterloo.ca/~acosenti/"
# twitter_username: jekyllrb
github_username:  cosenal
wordpress_url: "http://algorithmsforthekitchen.org/blog/"
strava_id: 4229739

# Build settings
markdown: kramdown
permalink: pretty

collections:
    papers:
        output: true
