# Site settings
name: Alessandro Cosentino
email: 
description: "The personal website of Alessandro Cosentino."
author: Alessandro Cosentino
baseurl: ""
url: "https://cosenal.github.io"
github_username:  cosenal
wordpress_url: "http://algorithmsforthekitchen.org/blog/"
strava_id: 4229739

include: [.well-known]

# Build settings
markdown: kramdown
permalink: pretty

paginate:    3
paginate_path: "page:num"

collections:
    papers:
        output: true
        layout: "paper"
    projects:
        output: true
        layout: "project"

gems:
    - jekyll-feed

