# Site settings
title: Alessandro Cosentino
email: 
description: "PhD student"
baseurl: ""
url: "https://cosenal.github.io"
github_username:  cosenal
wordpress_url: "http://algorithmsforthekitchen.org/blog/"
strava_id: 4229739

# Build settings
markdown: kramdown
permalink: pretty

collections:
    papers:
        output: true
    projects:
        output: true


